nome = input('Nome: ')
idade = int(input('Idade: '))
peso = str(input('Peso/Kg: '))
print('')
print('Seja bem vindo {}'.format(nome))
print('Você tem {} anos'.format(idade))
print('E pesa {}kg'.format(peso))